name: crownstonehub-ilhan-test2
version: '2.20'
architectures:
 - build-on: amd64
   run-on: armhf
summary: hello world
description: |
  says hello world
grade: stable
confinement: strict

apps:
 hello:
  command: bin/hello
 bash:
  command: bash

parts:
 gnu-hello:
  source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
  plugin: autotools
 gnu-bash:
  source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
  plugin: autotools
  configflags: ["--infodir=/var/bash/info"]


